name: Builds

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "*-workflow"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  setup_metadata:
    uses: ./.github/workflows/setup_metadata.yml
  build_linux:
    needs: [lint, setup_metadata]
    uses: ./.github/workflows/build_linux.yml
  build_macos:
    needs: [lint, setup_metadata]
    uses: ./.github/workflows/build_macos.yml
  build_windows:
    needs: [lint, setup_metadata]
    uses: ./.github/workflows/build_windows.yml
  bundle:
    needs: [build_linux, build_macos, build_windows, setup_metadata]
    uses: ./.github/workflows/bundle.yml